#!/bin/bash
# Sprint 8 - Delete non-PRD tests
# Generated by analyze_test_coverage.py

rm -f tests/safety/test_hara_coverage.py
rm -f tests/backend/integration/test_field_test_service.py
rm -f tests/backend/integration/test_gcs_integration.py
rm -f tests/backend/integration/test_phase1_integration.py
rm -f tests/backend/integration/test_analytics_export.py
rm -f tests/backend/integration/test_homing_integration.py
rm -f tests/backend/integration/test_app.py
rm -f tests/backend/integration/test_app_initialization.py
rm -f tests/backend/unit/test_prometheus_metrics.py
rm -f tests/backend/unit/test_ci_cd_pipeline.py
rm -f tests/backend/unit/test_phase2_coverage_boost.py
rm -f tests/backend/unit/test_deployment_config.py
rm -f tests/backend/unit/test_flaky_detector.py
rm -f tests/backend/unit/test_report_generator.py
rm -f tests/backend/unit/test_recommendations_engine.py
rm -f tests/backend/unit/test_main.py
rm -f tests/performance/test_performance_analytics.py
rm -f tests/integration/test_field_test_service.py
rm -f tests/integration/test_performance_validation.py
rm -f tests/integration/test_integration.py
rm -f tests/integration/api/test_api_analytics.py
rm -f tests/integration/api/test_analytics_api.py
rm -f tests/unit/test_state_refactored.py
rm -f tests/unit/mocks/test_mock_mavlink_connection.py
rm -f tests/unit/services/test_mission_replay_service.py
rm -f tests/e2e/test_production_build.py
rm -f tests/sitl/test_ardupilot_sitl_integration.py
rm -f tests/sitl/test_safety_scenarios.py
rm -f tests/contract/test_api_contracts.py
