# PISAD Default Configuration
# All configuration keys use UPPER_SNAKE case as per coding standards

# Application settings
APP_NAME: "PISAD"
APP_VERSION: "1.0.0"
APP_ENV: "development"
APP_HOST: "0.0.0.0"
APP_PORT: 8000

# SDR Configuration
SDR_FREQUENCY: 433920000  # Default frequency in Hz (433.92 MHz)
SDR_SAMPLE_RATE: 2048000  # Sample rate in Hz (2.048 MHz)
SDR_GAIN: 30  # Gain in dB
SDR_PPM_CORRECTION: 0  # Frequency correction in PPM
SDR_DEVICE_INDEX: 0  # RTL-SDR device index
SDR_BUFFER_SIZE: 16384  # Buffer size for SDR reads

# Signal Processing
SIGNAL_RSSI_THRESHOLD: -70  # RSSI threshold in dBm for signal detection
SIGNAL_AVERAGING_WINDOW: 10  # Number of samples for moving average
SIGNAL_MIN_DURATION_MS: 100  # Minimum signal duration in milliseconds
SIGNAL_MAX_GAP_MS: 50  # Maximum gap in signal to consider continuous

# Interferometry Configuration
INTERFEROMETRY_ENABLED: false  # Enable interferometric processing
INTERFEROMETRY_BASELINE_MM: 200  # Antenna baseline in millimeters
INTERFEROMETRY_CALIBRATION_FILE: "config/calibration.yaml"

# Database Configuration
DB_PATH: "data/pisad.db"
DB_CONNECTION_POOL_SIZE: 5
DB_ENABLE_WAL: true  # Enable Write-Ahead Logging for better concurrency

# Logging Configuration
LOG_LEVEL: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_FILE_PATH: "logs/pisad.log"
LOG_FILE_MAX_BYTES: 10485760  # 10 MB
LOG_FILE_BACKUP_COUNT: 5
LOG_ENABLE_CONSOLE: true
LOG_ENABLE_FILE: true
LOG_ENABLE_JOURNAL: true  # systemd journal integration

# WebSocket Configuration
WS_RSSI_UPDATE_INTERVAL_MS: 100  # RSSI update interval in milliseconds
WS_HEARTBEAT_INTERVAL_S: 30  # WebSocket heartbeat interval in seconds
WS_MAX_CONNECTIONS: 10  # Maximum concurrent WebSocket connections

# Safety Configuration
SAFETY_VELOCITY_MAX_MPS: 2.0  # Maximum velocity in meters per second
SAFETY_INTERLOCK_ENABLED: false  # Enable safety interlock system
SAFETY_EMERGENCY_STOP_GPIO: 23  # GPIO pin for emergency stop

# Performance Configuration
PERF_WORKER_THREADS: 4  # Number of worker threads
PERF_ENABLE_PROFILING: false  # Enable performance profiling
PERF_CACHE_SIZE_MB: 100  # In-memory cache size in MB

# API Configuration
API_RATE_LIMIT_ENABLED: false  # Enable rate limiting
API_RATE_LIMIT_REQUESTS: 100  # Requests per minute
API_CORS_ENABLED: true  # Enable CORS
API_CORS_ORIGINS: ["*"]  # Allowed CORS origins
API_KEY_ENABLED: false  # Enable API key authentication
API_KEY: ""  # API key (leave empty to disable)

# System Monitoring
MONITORING_ENABLED: false  # Enable Prometheus metrics
MONITORING_PORT: 9090  # Prometheus metrics port
MONITORING_INTERVAL_S: 60  # Metrics collection interval

# Development Settings
DEV_HOT_RELOAD: true  # Enable hot reload in development
DEV_DEBUG_MODE: false  # Enable debug mode
DEV_MOCK_SDR: false  # Use mock SDR for testing without hardware